# Generated by Django 4.2.5 on 2023-10-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, null=True, verbose_name='Category title')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category/images')),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000, null=True, verbose_name='Company name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='company/images', verbose_name='Company Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, null=True, verbose_name='Location name')),
            ],
        ),
        migrations.CreateModel(
            name='subsection',
            fields=[
                ('subsection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000, null=True, verbose_name='Job recruitment type')),
            ],
        ),
        migrations.CreateModel(
            name='testimony',
            fields=[
                ('testimony_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000, null=True, verbose_name='Testimonial name')),
                ('testimonies', models.TextField(verbose_name='Testimony')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimony/images', verbose_name='Testimonial Picture')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.category', verbose_name='job category')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2000, null=True, verbose_name='Job title')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('requirement', models.TextField(verbose_name='Job Requirement')),
                ('responsibilities', models.TextField(verbose_name=' Responsibilities')),
                ('sex', models.CharField(choices=[('Male', 'male'), ('Female', 'Female'), ('Both', 'Both'), ('None', 'None')], max_length=20, null=True, verbose_name='Gender for the job')),
                ('skill', models.CharField(max_length=2000, null=True, verbose_name='Job expected skills')),
                ('pay', models.IntegerField()),
                ('url', models.CharField(max_length=2000, null=True, verbose_name='Google form iframe link')),
                ('uploaded', models.DateField(auto_now=True, null=True)),
                ('deadline', models.DateField(verbose_name='Application deadline')),
                ('image', models.ImageField(blank=True, null=True, upload_to='job/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.location')),
            ],
        ),
    ]
