# Generated by Django 4.2.5 on 2023-10-02 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webpages.subsection'),
        ),
        migrations.AlterField(
            model_name='job',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both'), ('None', 'None')], max_length=20, null=True, verbose_name='Gender for the job'),
        ),
    ]
