# Generated by Django 4.2.5 on 2023-10-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_job_sub_alter_job_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
